packages:
  - packages/*

catalog:
  '@eslint/js': ^9.39.2
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  knip: ^5.82.1
  prettier: ^3.8.1
  prettier-plugin-organize-imports: ^4.3.0
  turbo: ^2.7.5
  typescript-eslint: ^8.53.1
